### ISSUE TITLE
webp_apng_exporter_for_AE 不能兼容CC2019是否有更新版本？

### ISSUE THREAD

**Issue by DesignerX** [bigxixi/webp_apng_exporter_for_AE#1]
![image](https://user-images.githubusercontent.com/30826174/60157092-8dfc2c00-9820-11e9-869d-d1c5f7e06664.png)

**Comment by bigxixi** [comment]
@DesignerX 你的系统版本是？待我找个环境测试一下。。。

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60158077-d583b780-9822-11e9-85c0-f3c7013cab03.png)
麻烦了

**Comment by bigxixi** [comment]
@DesignerX 你试试运行「终端」，输入
`defaults write com.adobe.CSXS.9 PlayerDebugMode 1`
再安装。
![屏幕快照 2019-06-26 下午3 03 12](https://user-images.githubusercontent.com/22438240/60158836-74f57a00-9824-11e9-925d-b315c460e2b5.jpg)
<img width="682" alt="屏幕快照 2019-06-26 下午3 03 06" src="https://user-images.githubusercontent.com/22438240/60158893-8e96c180-9824-11e9-99fc-ebf4b16258b5.png">

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60159037-e0d7e280-9824-11e9-8d34-c000d99455c0.png)
![image](https://user-images.githubusercontent.com/30826174/60159196-3f9d5c00-9825-11e9-94c8-05e22ff357b0.png)
还是不可以

**Comment by bwcx007** [comment]
感谢分享,Ae 2018CC导出来是png序列，是我哪里的姿势不对吗

**Comment by bigxixi** [comment]
@DesignerX 感觉是你的AE没有被zxp安装工具识别出来。。。你用的是这里下的最新版吗？
https://aescripts.com/learn/zxp-installer/

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60161816-d4ef1f00-982a-11e9-8e86-a13edea5d986.png)
是下载的最新版，而且  我还用了adobe的这款软件也不行，一下是截图：
![image](https://user-images.githubusercontent.com/30826174/60161902-fb14bf00-982a-11e9-8483-323b041308de.png)
![image](https://user-images.githubusercontent.com/30826174/60161951-1a135100-982b-11e9-9c6f-5366b97e97c7.png)

**Comment by bigxixi** [comment]
这样啊。。我需要点时间测试一下，如果急需需要导出这两个格式也可以看看我之前弄的工具，不过是要先导出序列帧，相对麻烦点
https://github.com/bigxixi/img2webp-and-apng-mac-automator

**Comment by DesignerX** [comment]
不着急，今天看到这款插件想试用一下遇到了问题，十分感谢慷慨分享，我会持续关注

**Comment by bigxixi** [comment]
@DesignerX 我这看到一个方案，你试试，英文大意是把图中这app删了
<img width="727" alt="屏幕快照 2019-06-26 下午4 03 56" src="https://user-images.githubusercontent.com/22438240/60162414-0d432d00-982c-11e9-9976-74293bf89ae6.png">

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60163312-e71e8c80-982d-11e9-92f4-e2574fea7b86.png)
您好  我没有找到您截图里面的这个，enmmm...

**Comment by bigxixi** [comment]
@DesignerX 那试试手工安装吧。。。
首先打开「终端」，输入
`defaults write com.adobe.CSXS.9 PlayerDebugMode 1`，回车（刚才你应该做过这一步了。。）
然后将 BX-WebpApngExporter.zxp 改成 BX-WebpApngExporter.zip，并解压
然后把解压后的文件复制到
`/Library/Application Support/Adobe/CEP/extensions/`
再重启AE试试

**Comment by bigxixi** [comment]
@DesignerX 是复制解压后的 com.bigxixi.WebpApngExporter 这个整个文件夹过去

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60165312-acb6ee80-9831-11e9-8b10-27cc21650674.png)
![image](https://user-images.githubusercontent.com/30826174/60165362-bb9da100-9831-11e9-8829-9eff6397686e.png)
![image](https://user-images.githubusercontent.com/30826174/60165405-cfe19e00-9831-11e9-98cd-e6c98a6fa600.png)
![image](https://user-images.githubusercontent.com/30826174/60165473-ee479980-9831-11e9-97ca-1288256f3f95.png)
enmmmm...有点鸡肋

**Comment by bigxixi** [comment]
@DesignerX 是复制到这里
<img width="1280" alt="屏幕快照 2019-06-26 下午4 54 07" src="https://user-images.githubusercontent.com/22438240/60166110-1388d780-9833-11e9-815b-03d0f2947b03.png">

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60166583-06b8b380-9834-11e9-9507-10afb372550c.png)
![image](https://user-images.githubusercontent.com/30826174/60166715-3ff12380-9834-11e9-817c-8d075b5e783d.png)

**Comment by bigxixi** [comment]
姨你解压出来的文件夹不是叫 com.bigxixi.WebpApngExporter 吗？里面是还有一层文件夹还是有很多文件

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60225919-732ac580-98bb-11e9-8ca3-b562306ed520.png)
我把文件复制错了，呃呃呃...sorry，重新试了一遍终端，复制文件，打开AE，还是不行....
![image](https://user-images.githubusercontent.com/30826174/60225997-de749780-98bb-11e9-9d2c-40a3c604f3d2.png)
我卸载AE试一下

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60227175-dd923480-98c0-11e9-89b3-85f6d73c94b3.png)

**Comment by bigxixi** [comment]
[捂脸]奇怪了。。你安装 AEUX、Bodymovin 的时候都正常吗？

**Comment by DesignerX** [comment]
都正常😭

**Comment by bigxixi** [comment]
@DesignerX 解压缩附件，然后用安装器安装一下这个版本试试

[com.bigxixi.WebpApngExporter.zxp.zip](https://github.com/bigxixi/webp_apng_exporter_for_AE/files/3332720/com.bigxixi.WebpApngExporter.zxp.zip)

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60233108-96606f80-98d1-11e9-9666-f5e252ad2c75.png)
开心

**Comment by DesignerX** [comment]
![image](https://user-images.githubusercontent.com/30826174/60240841-9158eb80-98e4-11e9-9a18-96cdafed9639.png)
![image](https://user-images.githubusercontent.com/30826174/60241242-691dbc80-98e5-11e9-8929-e437275a10b2.png)
可以了大神   已经可以正常使用，非常感谢
